### ISSUE TITLE
Startup Inconsistent cli vs vscode

### ISSUE THREAD

**Issue by corbanb** [R35007/Mock-Server#3]
# Overview

As I have been working on getting setup I am running into a few inconsistencies I will outline here. 

```bash
$ node -v
v16.17.0

$ npm -v
8.15.0
```

### Example startup tests (see below)
1. CLI using mock-server.json
2. CLI using params
3. Running via VSCode

### server.js and mock-server.json files
```js
// server.js

const { MockServer } = require("@r35007/mock-server");
const db = require("./data/db");
const config = require("./mock-server.json");
console.log("-----------------config");
console.log(config);
console.log("-----------------config");

const log = config.logger; // Set to true to see logs. If quiet is false the we cant see the setter logs.

const config = {
  root: __dirname,
  port: config.port,
  host: config.host,
  quiet: config.quiet,
};
const mockServer = MockServer.Create(config);

const app = mockServer.app;

// Sets global injectors, middlewares and store
mockServer.setData(
  {
    injectors: config.injectors,
    middlewares: config.middlewares,
    store: config.store,
  },
  { log }
); // pass mockServer instance to use it in middleware.js method

// Make sure to use this at first, before all the resources
const rewriter = mockServer.rewriter(config.rewriters); // Give Rewriters path or object here

// Returns the default middlewares
const defaultsMiddlewares = mockServer.defaults();

// add your authorization logic here
const isAuthorized = (_req) => true;

// Custom Middleware
app.use((req, res, next) => {
  if (isAuthorized(req)) return next(); // continue to Mock Server router
  res.sendStatus(401);
});

// Creates resources and returns the express router
const resources = mockServer.resources(db, { log });
console.log(resources);

// Create the Mock Server Home Page
const homePage = mockServer.homePage({ log });

app.use(rewriter);
app.use(defaultsMiddlewares);
app.use(resources.router);
app.use(homePage);
app.use(mockServer.pageNotFound); // Middleware to return `Page Not Found` as response if the route doesn't match
app.use(mockServer.errorHandler); // Default Error Handler

// mockServer.startServer();
mockServer.startServer(config.port, config.host); // can also set port and host here
```

```js
// mock-server.json
{
    "port": 3002,
    "host": "localhost",
    "base": "",
    "id": "id",
    "dbMode": "mock",
    "static": "public",
    "reverse": false,
    "logger": true,
    "noCors": false,
    "noGzip": false,
    "readOnly": true,
    "bodyParser": true,
    "cookieParser": true,
    "quiet": false,
    "db": "./data/db.js",
    "rewriters": "./rewriters.json",
    "injectors": "./injectors.json",
    "store": "./store.json",
    "middlewares": "./middlewares.js"
}
```

# Mock-Server startup Examples

## 1. CLI (mock-server.json)
Notice here: PORT does not persist to 4000. Also no logs in my server.js are seen in the console
![Screenshot 2022-11-04 at 1 43 54 PM](https://user-images.githubusercontent.com/140186/200062147-5c46a359-4aff-4077-802d-2c888613c8f2.png)

Homepage: 
- no database
- no rewriters
![Screenshot 2022-11-04 at 1 52 44 PM](https://user-images.githubusercontent.com/140186/200063167-f6906796-20f2-44b5-ac19-71e8ce56667a.png)

## 2. CLI w/ params

```bash
$ mock-server --watch ./data/db.js --rw=./rewriters.json --st=./store.json --md=middlewares.js --P=4000 -l=true -q=false    
```

Notice here: No logs again, but port 4000 is shown
![Screenshot 2022-11-04 at 1 49 13 PM](https://user-images.githubusercontent.com/140186/200062611-e33a3e8e-b0c4-4fd9-bb83-73972fc6ab7b.png)

Homepage: All databases AND rewriters are shown
- /products - works as expected
- /api/products - works as expected
- /api/products/45345454 - 404s
![Screenshot 2022-11-04 at 1 50 26 PM](https://user-images.githubusercontent.com/140186/200062818-fe30de81-2592-4e1b-8773-d0abdc65858c.png)

## 3. VSCode "Mock It" Button

- App starts at PORT 3001??
- Where would I see the logs if I could?

Homepage:
- Shows db and rewriters
- Same issue with routes as example 2

![Screenshot 2022-11-04 at 1 53 47 PM](https://user-images.githubusercontent.com/140186/200063508-11403cda-221c-4d29-961b-f3e56457e1fb.png)

I think this outlines the startup pretty well. As you can see I moved all configs in `server.js` to load from the `mock-server.json` but its not following that during startup for whatever reason. I would be able to debug further but unable to get any logging to work even when I hard code `quiet=false` and `log=true`. 

Thanks again. Hope this helps others.

**Comment by corbanb** [comment]
Let me know if you want the full code again. Maybe I can email to make that easier for you.

**Comment by R35007** [comment]
# 1. Logger 
Setting `logger` to true will not log the setter logs instead it is meant for to log the only Api calls if `process.env.NODE_ENV` is in `test` mode. When you hit any endpoint it logs those details in the terminal. While using CLI command the sertter log is always off. I will try to implement that. Summary: `logger` is not same as `log`. `logger` - to log api calls, `log` - to log setter method logs.

![image](https://user-images.githubusercontent.com/23217228/200108237-1e282036-79ff-4688-8208-d84e40631639.png)

I will add `log` param to CLI config to log setters in the next release

# 2 . Inconsistent Config
 The CLI is different from server.js. running `mock-server` in CLI won't run the `server.js` file. The `server.js` is to write our custom code with the given `mock-server` api methods.

All the config in both `CLI` and `server.js` are same except the paths that we provide is only ment for `CLI` and it wont affect the `server.js` code

# 3. Port issue
I can't able to replicate the port issue. For me the server runs as per the port mentioned in `mock-server.json`.  Still If we try to run `server.js` file it won't consider the `mock-server.json` config file. Both are not connected.

# 4. VS Code Extension Logs
Since VS Code Mock Server Extension uses the `@r35007/mock-server` package internally, there isnt any vscode extesnion api to expose the terminal logs that are generated by the node packages. Still we can able to see those by opening developer tools in vscode ( Help > Toggle Developer Tools ).

The Extension command logs can be seen thru `Mock Server Log` in the vscode Output panel.

![image](https://user-images.githubusercontent.com/23217228/200068944-a34ed1e8-5264-42e5-9a0b-3ba0c0ac151b.png)

# 4. Route Issue
Since the db route is set to `/products`, tying to accsees route `/products/45345454` - won't work. we need to give a route that accepts a route param as follows
```js
const db = {
 "/products/:id?": { /* Your Data here */  }
}
```

By this way we can access both `/products` and `/products/45345454`.

Note: Even if we can access ``/products/45345454` - the response wont be filtered as per param id. To do so we need to inject the predefined helper middlewares to do it as follows.

 ```js
const db = {
 "/products/:id?": { 
     _config: true,
     mock: {/* Your Data here */},
     middlewares: [ "_AdvancedSearch"  ]
  }
}
```

This `_AdvancedSearch` middleware helps to filter record by its param id and much more functionalities like `sort`, `limit`, `page`, `filter` etc...

Now we can access the following endpoints
`/products`
`/products/45345454`
`/products?name=Table`
`/products?_limit=10` 
etc...

For more Helper middleware doc please click [here](https://r35007.github.io/Mock-Server/#helper-middlewares)

**Comment by R35007** [comment]
@corbanb. 
Have updated the node package to `@r35007/mock-server@11.2.0` and vscode extesnsion to `version 11.2.2`
Now we can set `log` to true in `config` to see the setter logs. Also, I have added more sample files in vscode extension

**Comment by R35007** [comment]
Hi @corbanb ,
Can we close this ticket ?

**Comment by R35007** [comment]
Closing this ticket.
